name: MakeCode

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          npm install -g pxt
          pxt target arcade
          mkdir -p artifacts
      - name: build samd51
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
          cp built/binary.uf2 artifacts/samd51.uf2
        env:
          CI: true
      - name: build stm32f401
        run: |
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
          cp built/binary.uf2 artifacts/stm32f401.uf2          
      - name: build rpi
        run: |
          pxt clean
          pxt install --hw rpi
          pxt build --hw rpi --cloud
          cp built/binary.uf2 artifacts/rpi.uf2          
        env:
          CI: true
      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: uf2s
          path: artifacts
